name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v7
        with:
          node-version: 'lts/*'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Start mock server
        run: npm run start:mock-server &

      - name: Run tests
        run: npm run test

      - name: Lint
        run: npm run lint

      - name: Compile
        run: npm run compile

      - name: Release
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        uses: cycjimmy/semantic-release-action@v6
